# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171010_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('num_adults', models.IntegerField()),
                ('num_kids', models.IntegerField()),
                ('where', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('currency', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=10000)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
    ]
