# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_specialoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerspage',
            name='test',
            field=models.TextField(blank=True, max_length=40, verbose_name='Заголовок'),
        ),
    ]
