# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_offerspage_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerspage',
            name='intro_body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='offerspage',
            name='test',
            field=models.TextField(blank=True, max_length=40, verbose_name='Тест'),
        ),
    ]
