# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0011_testpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpage',
            name='test',
        ),
        migrations.AddField(
            model_name='testpage',
            name='carousel_title',
            field=models.TextField(blank=True, max_length=40, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='column1_body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, max_length=500, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='column1_header',
            field=models.CharField(blank=True, max_length=40, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='column2_body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, max_length=500, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='column2_header',
            field=models.CharField(blank=True, max_length=40, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='column3_body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, max_length=500, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='column3_header',
            field=models.CharField(blank=True, max_length=40, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='form_header',
            field=models.CharField(blank=True, max_length=40, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='form_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='form_intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, max_length=500, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='intro_hashtags',
            field=models.TextField(blank=True, max_length=40, verbose_name='Хэштэги'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='intro_header',
            field=models.TextField(blank=True, max_length=40, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='small_column1_body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, max_length=500, verbose_name='Текст 1'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='small_column1_header',
            field=models.CharField(blank=True, max_length=40, verbose_name='Заголовок 1'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='small_column2_body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, max_length=500, verbose_name='Текст 2'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='small_column2_header',
            field=models.CharField(blank=True, max_length=40, verbose_name='Заголовок 2'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='small_column3_body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, max_length=500, verbose_name='Текст 3'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='small_column3_header',
            field=models.CharField(blank=True, max_length=40, verbose_name='Заголовок 3'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='small_column4_body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, max_length=500, verbose_name='Текст 4'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='small_column4_header',
            field=models.CharField(blank=True, max_length=40, verbose_name='Заголовок 4'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='small_columns_intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, max_length=500, verbose_name='Общий текст'),
        ),
        migrations.AddField(
            model_name='testpage',
            name='small_columns_title',
            field=models.CharField(blank=True, max_length=40, verbose_name='Общий заголовок'),
        ),
    ]
