# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('home', '0012_auto_20171028_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpage',
            name='form_image',
        ),
        migrations.RemoveField(
            model_name='testpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='offerspage',
            name='intro_body',
        ),
        migrations.RemoveField(
            model_name='offerspage',
            name='test',
        ),
        migrations.DeleteModel(
            name='TestPage',
        ),
    ]
