# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0013_auto_20171028_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerspage',
            name='default_offer_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='text',
            field=wagtail.wagtailcore.fields.RichTextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='title',
            field=models.TextField(max_length=40, verbose_name='Заголовок'),
        ),
    ]
