# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 09:24
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20171029_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerspage',
            name='bottom_section_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, max_length=500, verbose_name='Нижняя секция'),
        ),
    ]
