# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_contact_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerspage',
            name='offers_intro',
        ),
        migrations.AddField(
            model_name='contact_page',
            name='bottom_section_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, max_length=500, verbose_name='Нижняя секция'),
        ),
        migrations.AddField(
            model_name='contact_page',
            name='text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, max_length=2000, verbose_name='Нижняя секция'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2017, 11, 6), verbose_name='Дата истечения'),
        ),
    ]
