# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_specofferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerspage',
            name='subtitle',
            field=models.TextField(blank=True, max_length=100, verbose_name='Подзаголовок'),
        ),
    ]
