# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 13:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_offerspage_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2017, 11, 7), verbose_name='Дата истечения'),
        ),
    ]
