# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 08:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20171031_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2017, 11, 15), verbose_name='Дата истечения'),
        ),
    ]
